package com.test.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BookDO extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.ISBN
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     * Database Column Remarks:
     *   书名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publication_date
     *
     * @mbg.generated
     */
    private Date publicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbg.generated
     */
    private String press;

    /**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.testNumber
     *
     * @mbg.generated
     */
    private Double testnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.ISBN
     *
     * @return the value of book.ISBN
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.ISBN
     *
     * @param isbn the value for book.ISBN
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publication_date
     *
     * @return the value of book.publication_date
     *
     * @mbg.generated
     */
    public Date getPublicationDate() {
        return publicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publication_date
     *
     * @param publicationDate the value for book.publication_date
     *
     * @mbg.generated
     */
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbg.generated
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbg.generated
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.testNumber
     *
     * @return the value of book.testNumber
     *
     * @mbg.generated
     */
    public Double getTestnumber() {
        return testnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.testNumber
     *
     * @param testnumber the value for book.testNumber
     *
     * @mbg.generated
     */
    public void setTestnumber(Double testnumber) {
        this.testnumber = testnumber;
    }
}